"""
ComponentsAgg — manufactured report aggregating the raw Components frame
by the standard payroll group key (JOIN_KEY, work_year, work_month,
employee_id).

For Phase 1a this is the canonical aggregation we use to validate the
end-to-end pipeline (LineageFrame.groupby + agg → ReferencingTableCells →
freeze → serialization). It deliberately covers only two aggregations
(total_amount sum, employee_name first) to keep the slice small; the
full port (with social_total enrichment) is part of Phase 1b.
"""
from Reports.Report import Report
from Headers import Headers
from Constants import GROUP_LIST


class ComponentsAgg(Report):
    def __init__(self, components_report, manager):
        super().__init__()
        self.id = "componentsAgg"
        self.display_label = "רכיבי שכר (מצרף)"
        self.is_input = False
        self.dependencies = ["components"]
        self.status = "error"

        if components_report is None or components_report.lineageFrame is None:
            self.status = "skipped"
            self.missing_dependencies = ["components"]
            return

        try:
            comp_h = Headers.InputFiles.Components
            src_frame = components_report.lineageFrame

            # ---- Aggregation ------------------------------------------
            # Group by the canonical payroll keys; sum the gross amount,
            # carry the employee name forward via 'first'.
            agg_map = {
                comp_h.total_amount:  "sum",
                comp_h.employee_name: "first",
            }
            agg_frame = src_frame.groupby(GROUP_LIST).agg(agg_map)

            # The output frame from groupby().agg() is itself registered
            # in the manager (the GroupBy code constructs it via
            # LineageFrame(...)). Promote it to this Report's lineageFrame.
            # Give it a stable report id so the wire payload references it
            # by 'componentsAgg' rather than the autogenerated label.
            agg_frame.report_id = self.id
            manager.frames_by_id[self.id] = agg_frame

            # ---- Authoring formula strings on each output column -----
            # Key columns: each output value is the "first" key-tuple of
            # its group, so the formula reads as a passthrough of the
            # source identifier (display-only — the value IS the key).
            for key_name in GROUP_LIST:
                col = agg_frame[key_name]
                col.formula = key_name           # plain identity label

            # Aggregated columns: render their agg name.
            agg_frame[comp_h.total_amount].formula  = f"sum({comp_h.total_amount})"
            agg_frame[comp_h.employee_name].formula = f"first({comp_h.employee_name})"

            self.lineageFrame   = agg_frame
            self.rows_count     = agg_frame.row_count()
            self.columns_count  = len(agg_frame.columns)
            self.status         = "loaded"

        except Exception as e:
            self.exceptions.append(f"{type(e).__name__}: {e}")
            # status remains 'error'
